# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
# Mod Properties
mod_version=0.0.1-dev
maven_group=org.aussiebox
archives_base_name=asterism
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.141.4+1.21.11
circuit_core_version=0.3.2
cca_version=7.3.2
geckolib_version=5.4.5
# DevAuth
devauth_module=fabric
devauth_version=1.2.2
